Error flow
iLCSoft/MarlinReco pull request #85
Opened 2021-01-22 10:53 UTC by yradkhorrami

1- An option added to enable/disable confusion term in the jet energy error
2- For scaling angular uncertainties of jets, CovMat of the jet is scaled by scaling factors.
3- So far, charged PFOs are identified by charge, so the energy of neutral PFOs with tracks is added to photons/neutral hadrons energy. Now it is changed to add the energy of neutral PFOs with tracks to the energy of charged PFOs.

2021-01-22 11:10 UTC, gaede commented
Please put some meaningful release notes into the commit comment, between
```
BEGINRELEASENOTES
...
ENDRELEASENOTES
```

2021-01-22 11:39 UTC, yradkhorrami commented
@gaede , Thanks. I hope that it's clear now.

2021-01-22 12:09 UTC, gaede commented
Thanks @yradkhorrami. I have just added a heading clarifying that this addresses the ErrorFlow proc...

2021-01-22 13:51 UTC, rete commented
@gaede We still hve this issue with TravisCI. We need to change the CI to github actions...

2021-01-22 14:05 UTC, gaede commented
Could you do this for MarlinReco and then the other packages as needed ?

2021-02-05 14:30 UTC, rete commented
@yradkhorrami Can you rebase please? We have a new CI working now :-)

2021-02-08 14:01 UTC, rete requested changes

2021-02-09 15:03 UTC, rete commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
@yradkhorrami ping

2021-02-09 17:24 UTC, yradkhorrami commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
@rete I did a bit cleaning up! is it ok?

2021-02-09 17:33 UTC, rete commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
It looks like the same. You still have additional tabs in the diffs

2021-02-09 18:07 UTC, yradkhorrami commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
@rete should be ok now. yes?

2021-02-09 18:46 UTC, rete commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
Look at the diffs. Not yet

2021-02-09 18:53 UTC, yradkhorrami commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
As I see, a lot of white spaces have been cleaned!
[](https://github.com/iLCSoft/MarlinReco/pull/85/commits/7e3df24ced23e5dd635e6277b00b8c2653228908)

2021-02-09 18:54 UTC, yradkhorrami commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
[](https://github.com/iLCSoft/MarlinReco/pull/85/commits/7e3df24ced23e5dd635e6277b00b8c2653228908)

2021-02-09 18:59 UTC, yradkhorrami commented on Analysis/ErrorFlow/include/ErrorFlow.h
> +	public:
@rete did you look at my latest commit?

2021-02-10 12:28 UTC, rete approved these changes

2021-02-10 12:28 UTC, merged